import { LESSON_STEPS, P2SH_STEPS } from './lessons';
import type { LessonStep } from './lessons';
import type { LessonKind } from './types';

function step(id: string, short: string, title: string, description: string, insight: string, pseudo: string, outputLabel: string): LessonStep {
  return { id, short, title, description, insight, pseudo, outputLabel, eyebrow: short.toUpperCase(), operation: short };
}

const compressed = { ...LESSON_STEPS[0], description: 'Serialize the public key in compressed SEC form: a parity prefix and a 32-byte x coordinate.', insight: 'Standard SegWit v0 relay policy requires compressed public keys. This lesson accepts 33-byte SEC keys beginning with 02 or 03.', pseudo: 'public_key = serialize_compressed(key)' };
const keyHash = { ...LESSON_STEPS[2], insight: 'This is the same HASH160 used for a compressed-key P2PKH address. Here it becomes a version-0 witness program.', pseudo: 'program = RIPEMD160(key_digest)', outputLabel: '20-byte witness program' };
const witnessOutput = step('output-script', 'Output script', 'A version and a program.', 'Create the locking script from a witness-version opcode and a direct push of the program bytes.', 'The program is the pushed data. The version opcode and push-length opcode belong to the surrounding script. Addresses encode the version and program separately.', 'output_script = witness_script(version, program)', 'Witness output · scriptPubKey');
const network = step('network', 'Network', 'A readable network prefix.', 'Choose bc for mainnet or tb for testnet. These letters appear before the separator in the address.', 'Changing networks changes the prefix and checksum. The witness program and locking script stay exactly the same.', 'hrp = network_prefix(network)', 'Network prefix · ASCII bytes');
const groups = step('groups', 'Five-bit groups', 'Give every five bits a character.', 'Regroup the witness program from eight-bit bytes into five-bit values. Prepend one value for the witness version.', 'Each value is between 0 and 31 and maps to one alphabet character. A 20-byte program needs no padding; a 32-byte program needs four zero padding bits.', 'data = [version] + convert_bits(program, 8, 5)', 'Five-bit values → characters');
const checksum = step('checksum', 'Checksum', 'Six characters to catch errors.', 'The Bech32 checksum covers the human-readable prefix, witness version, and converted program.', 'These are six five-bit symbols: 30 checksum bits, not six bytes and not a truncated SHA-256 hash. Version 0 uses Bech32.', 'checksum = bech32_checksum(hrp, data)', 'Six checksum symbols');
const encoded = step('address', 'Address', 'A SegWit address you can read.', 'Combine the network prefix, separator, version character, encoded program, and checksum.', 'In bc1q, bc is the network prefix, 1 is the separator, and q represents witness version 0. Native P2WPKH and P2WSH both start this way.', 'address = bech32(hrp, data, checksum)', 'Your native SegWit address');

export const P2WPKH_STEPS = [compressed, LESSON_STEPS[1], keyHash, witnessOutput, network, groups, checksum, { ...encoded, outputLabel: 'Your P2WPKH address' }];
export const P2WSH_STEPS = [
  { ...P2SH_STEPS[0], id: 'witness-script', short: 'Witness script', title: 'The same rule, carried in witness.', description: 'Build an m-of-3 multisig witness script. Its serialized bytes match the same multisig rule from the P2SH lesson.', insight: 'The name describes where the script is revealed during spending: in the witness. Key order and the signature threshold are part of its bytes.', pseudo: 'script_bytes = serialize(multisig(required, keys))', outputLabel: 'Serialized witness script' },
  step('sha256', 'SHA-256', 'One hash. Thirty-two bytes.', 'Hash the complete witness script once with SHA-256. Its 32-byte digest is the witness program.', 'P2SH uses HASH160(script), while P2WSH uses SHA256(script). There is no RIPEMD-160 step in this lesson.', 'program = SHA256(script_bytes)', '32-byte witness program'),
  witnessOutput, network, groups, checksum, { ...encoded, outputLabel: 'Your P2WSH address' },
];
export const NESTED_STEPS = [
  compressed, LESSON_STEPS[1], keyHash,
  { ...witnessOutput, id: 'redeem-script', short: 'Redeem script', title: 'Wrap the witness program.', description: 'The 22-byte P2WPKH script becomes the redeem script for an outer P2SH output.', insight: 'The redeem script is 00 14 followed by the public-key hash. It is not the text of a bc1 address.', pseudo: 'redeem_script = witness_script(0, program)', outputLabel: 'Inner P2WPKH · redeem script' },
  step('script-hash', 'Script HASH160', 'Commit to the whole inner script.', 'Apply HASH160 to all 22 bytes of the serialized redeem script.', 'This is a second commitment: the inner program commits to the public key; the outer hash commits to the inner script.', 'redeem_hash = HASH160(serialize(redeem_script))', 'Outer redeem-script hash'),
  { ...P2SH_STEPS[3], pseudo: 'payload = p2sh_version + redeem_hash' },
  { ...LESSON_STEPS[5], description: 'Double-SHA-256 the versioned P2SH payload and take its first four bytes.', pseudo: 'checksum = SHA256(SHA256(payload))[:4]' },
  { ...LESSON_STEPS[7], title: 'SegWit behind a P2SH address.', description: 'Base58Check-encode the outer P2SH commitment. The sender sees a 3… address on mainnet, even though spending uses witness data.', insight: 'A 3… prefix alone cannot tell you whether an address wraps SegWit or another P2SH script. That becomes clear when the redeem script is revealed.', pseudo: 'address = P2SH(redeem_script)', outputLabel: 'Your P2SH-P2WPKH address' },
];
export const TAPROOT_STEPS = [
  step('internal-key', 'Internal key', 'Start with an x-only internal key.', 'Keep the 32-byte x coordinate and interpret it as the curve point P with even y.', 'The 02 and 03 compressed forms with the same x coordinate map to the same x-only internal key. This lesson constructs a key-path output with no script tree.', 'internal_key = x_only(key)', 'Internal key · x(P)'),
  step('tag-hash', 'Tag digest', 'Give the hash its own context.', 'Hash the ASCII tag TapTweak once with SHA-256.', 'Tagged hashing prefixes its message with two copies of this tag digest. This separates TapTweak from other uses of SHA-256.', 'tag_digest = SHA256("TapTweak")', 'SHA-256 of TapTweak'),
  step('tweak', 'TapTweak', 'Calculate the tweak.', 'Hash tag_digest || tag_digest || internal_key with SHA-256 using the library’s tagged-hash function.', 'With no script tree, no Merkle-root bytes are appended. An absent root is not 32 zero bytes. The internal key is still tweaked.', 'tweak = tagged_hash("TapTweak", internal_key)', 'TapTweak · 32-byte digest'),
  step('output-key', 'Output key', 'Turn the internal key into the output key.', 'The library computes Q = P + tG on secp256k1. The output program is the 32-byte x coordinate of Q.', 'P is normalized to even y before the addition. The address carries the tweaked output key, not the original internal key and not HASH160 of a key.', 'output_key = x(P + integer(tweak) × G)', 'Output key · x(Q)'),
  { ...witnessOutput, insight: 'Taproot uses witness version 1 with a 32-byte output key. Its script begins 51 20: OP_1 is byte 0x51, while the address’s five-bit version value is 1.' },
  network, groups,
  { ...checksum, description: 'Use the Bech32m checksum for the version-1 data.', insight: 'Bech32m changes the checksum constant to 0x2bc830a3. Version 0 requires Bech32; versions 1–16 require Bech32m. The encodings are not interchangeable.', pseudo: 'checksum = bech32m_checksum(hrp, data)' },
  { ...encoded, title: 'A Taproot address.', description: 'Encode the network, witness version 1, and tweaked x-only output key with Bech32m.', insight: 'In bc1p, p represents version 1. A Taproot address does not reveal whether the output also commits to a script tree. This example has no script tree.', pseudo: 'address = bech32m(hrp, data, checksum)', outputLabel: 'Your P2TR address' },
];

const comparisonDescriptions = [
  ['p2pkh', 'P2PKH', 'A direct public-key hash.', 'A signature and the compressed public key satisfy this legacy output.'],
  ['p2sh', 'P2SH', 'A hash of a single-key script.', 'For this comparison, the redeem script is <key> OP_CHECKSIG. The earlier P2SH lesson uses a different, multisig script.'],
  ['p2wpkh', 'P2WPKH', 'A native version-0 key hash.', 'The public-key hash matches P2PKH, but the locking script and spending rules differ.'],
  ['p2wsh', 'P2WSH', 'A SHA-256 script commitment.', 'The witness script is the same <key> OP_CHECKSIG script used in this table’s P2SH row. Its hash function and spending location differ.'],
  ['nested', 'Nested', 'P2WPKH inside P2SH.', 'The redeem script is the P2WPKH locking script. The outer address uses Base58Check; the signature is carried in witness.'],
  ['p2tr', 'P2TR', 'A tweaked x-only output key.', 'This key-path example uses a TapTweak with no script tree. A Schnorr signature authorizes the spend.'],
];
export const COMPARISON_STEPS = comparisonDescriptions.map(([id, short, title, description]) => step(id, short, title, description, 'The hex below is the actual scriptPubKey stored in an output. Script sizes exclude the transaction’s length prefix; they are not transaction sizes or fee estimates.', `address, script = derive_${id}(key)`, `${short} · address and locking script`));

interface LessonDefinition {
  nav: string; tag: string; title: string; accent: string; description: string;
  steps: readonly LessonStep[]; multisig?: boolean;
  summary?: string; spending?: string; experiments?: string[]; references: number[];
}
export const LESSON_ORDER: LessonKind[] = ['p2pkh', 'p2sh', 'p2wpkh', 'p2wsh', 'nested', 'p2tr', 'compare'];
export const TRANSACTION_ORDER = ['transaction', 'signing', 'execution', 'propagation', 'construction', 'mining', 'blocks'] as const;
export function isTransactionPage(kind: LessonKind): kind is typeof TRANSACTION_ORDER[number] { return (TRANSACTION_ORDER as readonly string[]).includes(kind); }
export const CATALOG: Record<LessonKind, LessonDefinition> = {
  execution: { nav: 'Script execution', tag: 'STACK', title: 'Follow the stack.', accent: 'Verify the spend.', description: 'Execute a signed P2PKH input. Watch each instruction prove—or reject—the authorization.', steps: [], references: [] },
  signing: { nav: 'Signing', tag: 'P2PKH', title: 'Authorize the spend.', accent: 'One input at a time.', description: 'Match each key to its previous output. Follow the digest into a signature and scriptSig.', steps: [], references: [] },
  propagation: { nav: 'Propagation & mempools', tag: 'RELAY', title: 'One transaction.', accent: 'Many independent nodes.', description: 'Watch your signed transaction spread and compare each node’s local view.', steps: [], references: [] },
  construction: { nav: 'Block construction', tag: 'CANDIDATE', title: 'From mempool', accent: 'to Merkle root.', description: 'Select transactions, build the coinbase, and follow their TXIDs into the header commitment.', steps: [], references: [] },
  mining: { nav: 'Mining & PoW', tag: 'PoW', title: 'A committed header.', accent: 'Search for proof of work.', description: 'Inspect the candidate’s 80-byte header and compare each nonce hash with the target.', steps: [], references: [] },
  blocks: { nav: 'Block propagation & confirmations', tag: 'BLOCKS', title: 'A block arrives.', accent: 'Nodes decide.', description: 'Follow a mined block through independent validation, chain updates, and confirmation depth.', steps: [], references: [] },
  transaction: { nav: 'Transaction anatomy', tag: 'P2PKH', title: 'A transaction,', accent: 'piece by piece.', description: 'Choose the coins. Create the outputs. Discover every byte of an unsigned P2PKH transaction.', steps: [], references: [] },
  p2pkh: { nav: 'Legacy address', tag: 'P2PKH', title: 'An address,', accent: 'byte by byte.', description: 'How does a public key become a Bitcoin address? Follow the transformation. Understand every piece.', steps: LESSON_STEPS, references: [] },
  p2sh: { nav: 'Script hash', tag: 'P2SH', title: 'An address for', accent: 'a spending rule.', description: 'Three keys. One rule. A single address. Discover how a script becomes a commitment.', steps: P2SH_STEPS, multisig: true, references: [13, 16] },
  p2wpkh: { nav: 'Native SegWit', tag: 'P2WPKH', title: 'A familiar hash.', accent: 'A new address.', description: 'Follow a public key into a witness program, then explore the characters of a Bech32 address.', steps: P2WPKH_STEPS, summary: 'OP_0 <20-byte public-key hash>. The script is 22 bytes; its witness program is the 20-byte hash.', spending: 'Native P2WPKH requires an empty scriptSig. The witness contains a signature and public key. Their hash and signature must satisfy the program; the signature is not stored in the address.', experiments: ['Switch networks: the program and output script stay fixed while the prefix and checksum change.', 'Inspect the five-bit groups: the leading 0 maps to q.', 'Compare the HASH160 with the P2PKH lesson using the same compressed key.'], references: [141, 143, 173] },
  p2wsh: { nav: 'Witness script', tag: 'P2WSH', title: 'A spending rule,', accent: 'carried by witness.', description: 'Bring the multisig rule into SegWit. One SHA-256 hash becomes a 32-byte witness program.', steps: P2WSH_STEPS, multisig: true, summary: 'OP_0 <32-byte SHA-256 hash>. The script is 34 bytes; its witness program is the 32-byte hash.', spending: 'Native P2WSH requires an empty scriptSig. For this multisig example, witness contains an empty CHECKMULTISIG dummy item, the required signatures in matching key order, and the witness script. Its SHA-256 must match the program before the script is executed.', experiments: ['Change the threshold or swap keys. Both the script and its hash change.', 'Compare the script bytes with P2SH; the same rule gets a different hash construction.', 'Inspect the last five-bit group: a 32-byte program needs four zero padding bits.'], references: [141, 143, 173] },
  nested: { nav: 'Nested SegWit', tag: 'P2SH-P2WPKH', title: 'A SegWit program,', accent: 'inside a script hash.', description: 'Follow two commitments: first to a public key, then to the script that wraps it.', steps: NESTED_STEPS, summary: 'The outer output is OP_HASH160 <redeem-script hash> OP_EQUAL. The redeem script is the 22-byte inner P2WPKH script.', spending: 'scriptSig must contain exactly a push of the serialized P2WPKH redeem script. The witness contains the signature and public key. The signature is not moved back into scriptSig by the P2SH wrapper.', experiments: ['Compare the inner redeem script with the native P2WPKH output: they match byte for byte.', 'Inspect the outer hash: it covers the 00 and 14 opcodes as well as the key hash.', 'A 3… mainnet address does not reveal whether its hidden redeem script uses SegWit.'], references: [16, 141] },
  p2tr: { nav: 'Taproot', tag: 'P2TR', title: 'From internal key', accent: 'to Taproot.', description: 'Explore x-only keys, the TapTweak commitment, and Bech32m in a key-path example with no script tree.', steps: TAPROOT_STEPS, summary: 'OP_1 <32-byte output key>. The script starts 51 20. Version 1 and the tweaked key are encoded separately in the Bech32m address.', spending: 'In this key-path example, scriptSig is empty and the witness carries a Schnorr signature checked against the tweaked output key. Taproot can also commit to script paths; constructing such trees is beyond this address lesson.', experiments: ['Replace 02 with 03, or vice versa, keeping x unchanged. The Taproot address stays the same because the internal key is x-only.', 'Switch networks: the tweak and output key stay unchanged.', 'Compare the internal and output keys. Even with no script tree, the output key is tweaked.'], references: [340, 341, 350] },
  compare: { nav: 'Compare addresses', tag: 'LAB', title: 'One public key.', accent: 'Six constructions.', description: 'Compare real addresses and locking scripts side by side. Follow what each construction commits to.', steps: COMPARISON_STEPS, references: [16, 141, 173, 341, 350] },
};

export function lessonFromHash(hash: string): LessonKind | null {
  const candidate = hash.replace(/^#/, '') || 'p2pkh';
  return isTransactionPage(candidate as LessonKind) || LESSON_ORDER.includes(candidate as LessonKind) ? candidate as LessonKind : null;
}
