import { useEffect, useState } from 'react';
import type { Network, SighashPreview, SighashType, TaprootPath, TaprootTree, TransactionDraft, TransactionResult } from './types';
import type { usePython } from './usePython';
import { pathDefaults } from './taprootExamples';
import './taproot.css';
import './execution.css';

type Input = TransactionDraft['inputs'][number];
const pathNames: Record<TaprootPath, string> = { key: 'Key path · one signature', multisig: '2-of-3 co-signers', recovery: 'Recovery after 144 blocks', hashlock: 'Secret + signature' };

export function TaprootControls({ row, index, tree, signing, change, changeTree }: { row: Input; index: number; tree: boolean; signing: boolean; change: (updates: Partial<Input>) => void; changeTree: (count: 2 | 3) => void }) {
  const path = tree ? row.taprootPath ?? 'multisig' : 'key';
  return <div className="taproot-controls">
    {tree ? <>
      <label>Script tree<select aria-label={`Input ${index + 1} script tree`} value={row.taprootLeaves ?? 2} onChange={e => changeTree(Number(e.target.value) as 2 | 3)}><option value="2">Two leaves · co-signers + recovery</option><option value="3">Three leaves · add a secret</option></select></label>
      <div className="taproot-path-choices" role="group" aria-label={`Input ${index + 1} spending path`}>{(['key', 'multisig', 'recovery', ...((row.taprootLeaves ?? 2) === 3 ? ['hashlock'] : [])] as TaprootPath[]).map(id => <button key={id} type="button" aria-pressed={path === id} onClick={() => change(pathDefaults(id))}>{pathNames[id]}</button>)}</div>
      <p className="tx-entry-note">Each leaf is an alternative way to spend. This teaching output also has a key path controlled by public learning key 1: it can spend immediately, without satisfying any leaf. Changing the tree creates a different output address.</p>
    </> : <label>Internal public key · x-only, 32-byte hex<input aria-label={`Input ${index + 1} internal key`} value={row.internalKey ?? ''} onChange={e => change({ internalKey: e.target.value })} spellCheck={false} /><span className="tx-entry-note">Use the internal key from <a href="#p2tr">Taproot Addresses</a>. The no-tree TapTweak must reproduce the previous output key.</span></label>}
    <label>Sequence · decimal<input aria-label={`Input ${index + 1} sequence`} value={row.sequence ?? '4294967295'} onChange={e => change({ sequence: e.target.value })} inputMode="numeric" /><span className="tx-entry-note">{path === 'recovery' ? '144 enables a delay of 144 blocks after this UTXO confirms. Script execution also checks the modeled UTXO age.' : '4294967295 is final. Choosing recovery sets this to 144.'}</span></label>
    {signing && (path === 'multisig' ? <>
      <p>Choose exactly two co-signers from public learning scalars 2, 3 and 4. Empty slots represent absent signatures; there is no CHECKMULTISIG dummy.</p>
      {[0, 1, 2].map(slot => <label key={slot}>Learning co-signer {slot + 1}<input aria-label={`Input ${index + 1} signer ${slot + 1} private key`} value={row.signerKeys?.[slot] ?? ''} onChange={e => change({ signerKeys: [0, 1, 2].map(i => i === slot ? e.target.value : row.signerKeys?.[i] ?? '') })} spellCheck={false} autoComplete="off" /></label>)}
    </> : <>
      <label>Learning private key · 32-byte hex<input aria-label={`Input ${index + 1} private key`} value={row.privateKey ?? ''} onChange={e => change({ privateKey: e.target.value })} spellCheck={false} autoComplete="off" /></label>
      <p className="tx-entry-note">{path === 'key' ? 'The example uses public learning key 1, tweaked for this output.' : path === 'recovery' ? 'The recovery leaf uses public learning key 5, without a key tweak.' : 'The hashlock leaf uses public learning key 6, without a key tweak.'} Keys stay in memory and appear in copied Python.</p>
      {path === 'hashlock' && <label>Secret · hex bytes<input aria-label={`Input ${index + 1} secret`} value={row.secret ?? ''} onChange={e => change({ secret: e.target.value })} spellCheck={false} /><span className="tx-entry-note">The example secret is “bit by bit”. Its SHA256 is committed inside the leaf.</span></label>}
    </>)}
  </div>;
}

function TreeConnectors() {
  return <svg className="taproot-tree-connectors" viewBox="0 0 100 24" preserveAspectRatio="none" aria-hidden="true"><path d="M50 0V8M25 8H75M25 8V24M75 8V24" fill="none" vectorEffect="non-scaling-stroke" /></svg>;
}
function LeafButton({ item, selected, inspect }: { item: TaprootTree['leaves'][number]; selected: boolean; inspect: () => void }) {
  return <button type="button" className={selected ? 'inspected' : ''} aria-pressed={selected} onClick={inspect}><span>{item.label}</span><small>TapLeaf · depth {item.proof.length}</small><code>{item.leafHash}</code></button>;
}

export function TaprootTreeExplorer({ trees, choose }: { trees: TaprootTree[]; choose: (index: number, path: TaprootPath) => void }) {
  const [inspected, setInspected] = useState<Record<number, TaprootPath>>({});
  return <section className="panel taproot-tree-lab" aria-label="Taproot commitment explorer"><span className="output-kicker">ONE OUTPUT · MORE THAN ONE WAY IN</span><h2>Follow the Taproot commitment</h2>
    {trees.map((tree, index) => {
      const leaf = tree.leaves.find(l => l.path === (inspected[index] ?? tree.path)) ?? tree.leaves[0];
      return <div key={index} className="taproot-tree-input"><h3>Input {index + 1} · {pathNames[tree.path]}</h3>
        <div className="taproot-commitment-chain"><div><span>Internal x-only key</span><code>{tree.internalKey}</code></div>{tree.leafCount > 0 && <div><span>Script-tree root · TapBranch</span><code>{tree.merkleRoot}</code></div>}<div><span>TapTweak · {tree.leafCount ? 'key + root' : 'key only, no script tree'}</span><code>{tree.tweak}</code></div><div><span>Tweaked output key · stored after 5120</span><code>{tree.outputKey}</code></div></div>
        {!!tree.leafCount && <><p>The internal key and tree root produce one output key. Each TapLeaf hash commits to c0 + CompactSize(script length) + script. TapBranch sorts its two child hashes before hashing.</p>
          <div className={`taproot-tree-diagram leaves-${tree.leafCount}`} aria-label="Script tree structure">
            <div className="taproot-root">TapBranch root</div><TreeConnectors />
            <div className="taproot-leaf-row">
              {tree.leafCount === 2 ? tree.leaves.map(item => <LeafButton key={item.path} item={item} selected={leaf?.path === item.path} inspect={() => setInspected(previous => ({ ...previous, [index]: item.path }))} />) : <>
                <LeafButton item={tree.leaves[0]} selected={leaf?.path === tree.leaves[0].path} inspect={() => setInspected(previous => ({ ...previous, [index]: tree.leaves[0].path }))} />
                <div className="taproot-inner-branch"><div className="taproot-root">TapBranch · recovery + secret</div><TreeConnectors /><div className="taproot-leaf-row">{tree.leaves.slice(1).map(item => <LeafButton key={item.path} item={item} selected={leaf?.path === item.path} inspect={() => setInspected(previous => ({ ...previous, [index]: item.path }))} />)}</div></div>
              </>}
            </div>
            {tree.branchHash && <p>Lower TapBranch hash: <code>{tree.branchHash}</code></p>}
          </div>
          {leaf && <div className="taproot-leaf-detail"><h3>{leaf.label}</h3><button type="button" className="secondary-button" onClick={() => choose(index, leaf.path)}>Use this spending path</button><h4>Only this script is revealed when this leaf is spent</h4><code className="tx-selected-hex">{leaf.script}</code><h4>Control block · {leaf.controlBlock.length / 2} bytes</h4><code className="tx-selected-hex">{leaf.controlBlock}</code><p>The first byte carries c0 plus output-key parity, then the 32-byte internal key and {leaf.proof.length} sibling {leaf.proof.length === 1 ? 'hash' : 'hashes'}. The other scripts stay hidden.</p>{leaf.proof.map((proof, i) => <div key={i}><h4>Sibling hash {i + 1} · proof step {i + 1}</h4><code className="tx-selected-hex">{proof}</code></div>)}</div>}
          <table className="taproot-size-table"><caption>Witness size for this input · selected SIGHASH mode</caption><thead><tr><th>Spending path</th><th>Witness bytes / WU</th><th>Revealed on chain</th></tr></thead><tbody><tr><td>Key path</td><td>{tree.keyWitnessBytes}</td><td>One signature</td></tr>{tree.leaves.map(item => <tr key={item.path}><td>{item.label}</td><td>{item.witnessBytes}</td><td>Arguments + chosen script + proof</td></tr>)}</tbody></table><p className="tx-entry-note">Counts include CompactSize prefixes. Each witness byte contributes one weight unit. The signed transaction’s full vsize is shown below. A key-path spend hides whether this tree even exists.</p>
        </>}
      </div>;
    })}
  </section>;
}

export function TaprootSighash({ index, mode, outputCount, expanded, toggle, change, preview, pendingMessage }: { index: number; mode: SighashType; outputCount: number; expanded: boolean; toggle: () => void; change: (value: SighashType) => void; preview?: SighashPreview['inputs'][number]; pendingMessage: string }) {
  const [selected, setSelected] = useState('hash_type');
  const field = preview?.taproot?.fields.find(f => f.name === selected) ?? preview?.taproot?.fields[0];
  return <div className="tx-sighash-explorer"><button className="tx-sighash-toggle" type="button" aria-expanded={expanded} onClick={toggle}><span>Explore signature scope</span><span className="tx-sighash-pill">{mode === 0 ? 'SIGHASH_DEFAULT · all inputs + outputs' : preview?.name ?? `Mode ${mode}`}</span></button>{expanded && <div className="tx-sighash-body"><p>Taproot signs a tagged TapSighash digest. DEFAULT has the scope of ALL and omits the type byte from the 64-byte Schnorr signature.</p><label>Signature scope<select aria-label={`Input ${index + 1} SIGHASH mode`} value={mode} onChange={e => change(Number(e.target.value) as SighashType)}>{([0, 1, 2, 3, 129, 130, 131] as SighashType[]).map(value => <option key={value} value={value} disabled={(value & 3) === 3 && index >= outputCount}>{value === 0 ? 'DEFAULT' : `${(value & 3) === 1 ? 'ALL' : (value & 3) === 2 ? 'NONE' : 'SINGLE'}${value & 128 ? ' + ANYONECANPAY' : ''}`}</option>)}</select></label>
    {index >= outputCount && <p>Taproot SINGLE requires a matching output. Add output {index + 1} in Anatomy.</p>}
    {preview?.type === mode ? <><div className="tx-sighash-scope"><div><span>Input outpoints + previous locks</span><strong>{preview.inputScope}</strong></div><div><span>Previous input amounts</span><strong>{preview.amountScope}</strong></div><div><span>Sequences</span><strong>{preview.sequenceScope}</strong></div><div><span>Outputs</span><strong>{preview.outputScope}</strong></div></div><p>Version and locktime are always committed. Without ANYONECANPAY, all input sequences, amounts, and previous locking scripts are committed—even with NONE or SINGLE. Script-path signatures also commit to the chosen TapLeaf.</p><div className="tx-sighash-digest"><span>BIP341 · Schnorr signing digest</span><code>{preview.digest}</code></div><h4>Exact tagged-hash message · {preview.preimage!.length / 2} bytes</h4><div className="taproot-message-fields">{preview.taproot?.fields.map(item => <button key={item.name} type="button" aria-pressed={field?.name === item.name} onClick={() => setSelected(item.name)}>{item.name}<small>{item.end - item.start} B</small></button>)}</div>{field && <div className="taproot-message-detail"><h4>{field.name} · bytes {field.start}–{field.end - 1}</h4><p>{field.description}</p><code className="tx-selected-hex">{field.hex}</code>{field.source && <details><summary>Bytes hashed with single SHA256</summary><code className="tx-selected-hex">{field.source}</code></details>}</div>}<details><summary>Full message · epoch + SigMsg + optional Tapscript extension</summary><p>digest = SHA256(SHA256(“TapSighash”) || SHA256(“TapSighash”) || message)</p><code className="tx-selected-hex">{preview.preimage}</code></details></> : <p role="status">{pendingMessage}</p>}
  </div>}</div>;
}

export function TaprootSigning({ data }: { data: TransactionResult }) {
  const signing = data.signing!;
  return <section className="panel tx-signing-results" aria-label="Signing walkthrough"><span className="output-kicker">BIP341 DIGEST → SCHNORR → WITNESS</span><h2>What did we sign?</h2><p>DEFAULT commits to all input outpoints, amounts, previous locks and sequences, every output, version and locktime. The library creates a BIP340 Schnorr signature. Key-path signing tweaks the internal private key; script-path signing uses untweaked leaf keys and includes a TapLeaf commitment in the digest.</p>
    {signing.inputs.map((item, index) => <details key={index} open={signing.inputs.length === 1}><summary>Input {index + 1} · {pathNames[item.taprootPath!]} · {item.sighashName}</summary><h4>Signing digest · 32 bytes</h4><code className="tx-selected-hex">{item.digest}</code><h4>{item.sighashType === 0 ? 'Schnorr signatures · 64 bytes, implied DEFAULT' : 'Schnorr signatures · 64 bytes + one nonzero SIGHASH byte'}</h4>{item.signatures?.map((sig, i) => <code key={i} className="tx-selected-hex">{sig}</code>)}<h4>Witness stack · {item.witness.length} items</h4>{item.witness.map((value, i) => <code key={i} className="tx-selected-hex">{i + 1}. {value || '(empty signature slot · absent co-signer)'}</code>)}<p>{item.taprootPath === 'key' ? 'Only the signature is revealed. The output already contains the verification key; no public-key witness item is needed.' : item.taprootPath === 'multisig' ? 'Three signature slots appear in reverse public-key order, followed by the script and control block. CHECKSIGADD counts valid signatures; no CHECKMULTISIG dummy is used.' : 'The witness contains the signature (and secret for a hashlock), followed by the selected script and its control block.'}</p><h4>scriptSig · empty, 0 bytes</h4></details>)}
    <div className="tx-size-comparison"><span>Unsigned <strong>{signing.unsignedBytes} bytes</strong></span><span>Signed <strong>{data.totalSize} bytes</strong></span><span>Fee sizing <strong>{data.vsize} vB</strong></span></div><h4>TXID · excludes witness</h4><code className="tx-selected-hex" data-testid="signed-txid">{data.txid}</code><p>Signing preserves the unsigned TXID because every scriptSig stays empty. Selecting recovery also changes sequence; that changes TXID before signing.</p><h4>WTXID · includes witness</h4><code className="tx-selected-hex" data-testid="signed-wtxid">{data.wtxid}</code><p>Continue to Script execution to verify the Schnorr signature or the selected script and its proof.</p><details><summary>Unsigned serialization and ID</summary><code className="tx-selected-hex">{signing.unsignedTxid}</code><code className="tx-selected-hex">{signing.unsignedHex}</code></details>
  </section>;
}

const explanations: Record<string, string> = {
  LOAD_SIGNATURE: 'Read the Schnorr signature from the witness.', LOAD_ARGUMENT: 'Load a witness argument into the initial Tapscript stack.',
  VERIFY_SCHNORR: 'Verify the BIP340 signature against the output key. Key-path validation does not execute a script.',
  CHECK_TAPROOT_PROOF: 'Hash the chosen leaf and its sibling hashes, then apply TapTweak. Check the reconstructed output key and parity against the previous lock.',
  OP_CHECKSIG: 'Verify the signature against this leaf’s x-only key. An empty signature contributes false; an invalid nonempty signature fails.',
  OP_CHECKSIGADD: 'Consume a signature and the running count. Add one for a valid signature, zero for an empty slot.',
  OP_NUMEQUAL: 'Compare the signature count with the required threshold of two.',
  OP_CHECKSEQUENCEVERIFY: 'Check that version and sequence enable at least 144 blocks of relative delay.',
  CHECK_RELATIVE_AGE: 'Check the modeled UTXO age against the sequence delay. This is a BIP68 context check, outside script execution.',
  OP_SHA256: 'Hash the secret witness argument with SHA256.', OP_EQUALVERIFY: 'Require the hash to match the value committed in this leaf.',
};
export function TaprootExecution({ runtime, trace, network }: { runtime: ReturnType<typeof usePython>; trace: { hex: string; data: TransactionResult }; network: Network }) {
  const [index, setIndex] = useState(0), [experiment, setExperiment] = useState('original'), [age, setAge] = useState('144');
  const [position, setPosition] = useState(0), [playing, setPlaying] = useState(false);
  const { calculate } = runtime;
  const { data, hex } = trace;
  const path = data.signing!.inputs[index].taprootPath!;
  useEffect(() => {
    setPosition(0); setPlaying(false);
    calculate({ kind: 'execution', publicKey: '', network, compressed: true, execution: { hex, previousScript: data.previousScripts[index], previousScripts: data.previousScripts, amount: data.previousAmounts[index], amounts: data.previousAmounts, spendType: data.spendType, inputIndex: index, experiment, age: /^[0-9]{1,9}$/.test(age) ? Number(age) : -1 } });
  }, [calculate, data, hex, network, index, experiment, age]);
  const result = runtime.trace?.execution;
  const step = result?.steps[position - 1];
  const done = !!result && position >= result.steps.length;
  useEffect(() => { if (!playing || !result || done) return; const timer = setTimeout(() => setPosition(p => p + 1), 1100); return () => clearTimeout(timer); }, [playing, result, done, position]);
  const stack = (label: string, values: string[]) => <section className="execution-stack"><h3>{label}</h3><span className="output-kicker">TOP OF STACK</span><div>{[...values].reverse().map((v, i) => <code key={i}>{v || '(empty · false)'}</code>)}{!values.length && <p>Empty stack</p>}</div></section>;
  return <section className="panel execution-lesson" aria-label="Taproot execution"><h2>{path === 'key' ? 'Verify the key-path signature' : 'Prove the leaf. Then satisfy it.'}</h2><p>{path === 'key' ? 'The witness has one signature. Verify it directly against the tweaked output key; there is no script to run.' : 'The control block proves that this output commits to the chosen script. Only then do its witness arguments enter Tapscript execution.'}</p><div className="mining-controls"><label>Input<select aria-label="Execution input" value={index} onChange={e => { setIndex(Number(e.target.value)); setExperiment('original'); }}>{data.previousScripts.map((_, i) => <option key={i} value={i}>Input {i + 1}</option>)}</select></label><label>Experiment<select aria-label="Execution experiment" value={experiment} onChange={e => setExperiment(e.target.value)}><option value="original">Original signed transaction</option><option value="signature">Alter a signature byte</option><option value="output">Increase output 1 by 1 satoshi</option><option value="amount">Change this previous amount</option>{data.previousAmounts.length > 1 && <option value="other-amount">Change another input’s previous amount</option>}{path !== 'key' && <><option value="control">Alter the control-block proof</option><option value="leaf">Change the revealed leaf</option></>}{path === 'multisig' && <><option value="order">Reverse the signature slots</option><option value="missing">Remove a co-signer</option></>}{path === 'recovery' && <><option value="early">Try at age 143 blocks</option><option value="sequence">Lower sequence to 143</option></>}{path === 'hashlock' && <option value="secret">Use the wrong secret</option>}</select></label>{path === 'recovery' && <label>Modeled UTXO age · blocks<input aria-label="Modeled UTXO age" value={age} onChange={e => setAge(e.target.value)} inputMode="numeric" /></label>}</div><p>Experiments use a copy and keep the selected signed transaction intact. This input uses {data.signing!.inputs[index].sighashName}; an edit only invalidates a signature when its digest commits to the edited data.</p>
    {result ? <><div className="execution-instructions" aria-label="Execution instructions"><button onClick={() => {setPosition(0); setPlaying(false);}}>Start</button>{result.steps.map((item, i) => <button key={i} aria-pressed={position === i + 1} className={position === i + 1 ? 'selected' : ''} onClick={() => {setPosition(i + 1); setPlaying(false);}}><small>{item.phase}</small>{item.instruction}</button>)}</div><div className="execution-current" aria-live="polite"><span className="output-kicker">{position} / {result.steps.length}</span><h3>{step ? explanations[step.instruction] ?? step.instruction : 'Begin with an empty stack.'}</h3></div><div className="execution-stacks">{stack('Before', step?.stack_before ?? [])}{stack('After', step?.stack_after ?? [])}</div>{step?.digest && <div className="execution-digest"><h3>BIP341 digest · Schnorr {step.signature_valid ? 'passed' : 'failed'}</h3><code>{step.digest}</code></div>}{done && <div className={`execution-verdict ${result.success ? 'passed' : 'failed'}`} role="status"><strong>{result.success ? 'This Taproot input succeeds' : 'Taproot validation failed'}</strong><p>{result.error ? `${result.error.code}: ${result.error.message}` : path === 'key' ? 'The output-key Schnorr signature verified.' : 'The commitment and selected spending condition passed, with one true final stack item.'}</p></div>}<div className="mining-controls"><button className="secondary-button" disabled={!position} onClick={() => {setPlaying(false); setPosition(p => p - 1);}}>Previous</button><button className="primary-button" disabled={done} onClick={() => {setPlaying(false); setPosition(p => p + 1);}}>Next instruction</button><button className="secondary-button" disabled={done} onClick={() => setPlaying(!playing)}>{playing ? 'Pause' : 'Play execution'}</button><button className="text-button" onClick={() => {setPlaying(false); setPosition(result.steps.length);}}>Show result</button></div><details className="mining-details"><summary>Python executed for this experiment</summary><pre>{result.python}</pre></details></> : <p role="status">{runtime.error ?? 'Preparing Taproot validation…'}</p>}
    <p className="tx-entry-note">Scope: seven Taproot SIGHASH modes, key-path Schnorr verification, and these three fixed c0 leaves. Script operations are grouped into explained checks. No annex, OP_CODESEPARATOR, arbitrary Tapscript or full node policy. UTXO locks, amounts and ages are supplied to the lab; no chain lookup or broadcast occurs.</p>
  </section>;
}
