import { useEffect, useRef, useState } from 'react';
import { Check, Copy, Clock3, LockKeyhole, RotateCcw } from 'lucide-react';
import type { LessonInput, Network, TimelockMode, TimelockOptions, TimelockResult, TimelockUnit } from './types';
import type { usePython } from './usePython';
import { matchingFields, relativeMode, TIMELOCK_MODES, timelockScenario } from './timelockScenarios';
import './timelocks.css';

const fmt = (n: number) => n.toLocaleString('en-US');
const date = (n: string) => /^\d+$/.test(n) && Number(n) <= 4294967295 ? new Date(Number(n) * 1000).toISOString().replace('T', ' ').replace('.000Z', ' UTC') : 'Enter Unix seconds.';
function CopyCode({ value, label }: { value: string; label: string }) {
  const [copied, setCopied] = useState(false);
  useEffect(() => setCopied(false), [value]);
  return <button className="text-button" onClick={async () => { try { await navigator.clipboard.writeText(value); setCopied(true); } catch { setCopied(false); } }}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Copied' : label}</button>;
}
export function TimelocksLab({ runtime, visible }: { runtime: ReturnType<typeof usePython>; visible: boolean }) {
  const [options, setOptions] = useState<TimelockOptions>(() => timelockScenario());
  const [network, setNetwork] = useState<Network>('mainnet');
  const [result, setResult] = useState<TimelockResult | null>(null);
  const pending = useRef<LessonInput | null>(null);
  const { calculate, invalidate } = runtime;
  const relative = relativeMode(options.mode), enforced = options.mode === 'cltv' || options.mode === 'csv';
  function run(next = options, net = network) {
    setResult(null);
    const input: LessonInput = { kind: 'timelocks', timelocks: next, network: net, compressed: true, publicKey: '' };
    pending.current = input; calculate(input);
  }
  useEffect(() => {
    if (visible) run();
    else pending.current = null;
    // Editing waits for an explicit build; returning to the lab rebuilds its own saved scenario.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible, calculate]);
  useEffect(() => {
    if (visible && pending.current === runtime.traceInput && runtime.trace?.timelocks) setResult(runtime.trace.timelocks);
  }, [visible, runtime.trace, runtime.traceInput]);
  function edit(patch: Partial<TimelockOptions>) { pending.current = null; invalidate(); setOptions(previous => ({ ...previous, ...patch })); setResult(null); }
  function preset(mode: TimelockMode, unit?: TimelockUnit) { const next = timelockScenario(mode, unit); setOptions(next); run(next); }
  function matching() { const next = matchingFields(options); setOptions(next); run(next); }
  function clock(boundary: 'before' | 'at') {
    if (!result) return;
    const next = { ...options, height: String(Math.max(Number(options.coinHeight) + 1, result.minimumHeight - (boundary === 'before' ? 1 : 0))),
      mtp: String(Math.max(Number(options.coinMtp), result.minimumMtp - (boundary === 'before' ? 1 : 0))) };
    setOptions(next); run(next);
  }
  function field(key: 'value' | 'locktime' | 'sequence' | 'height' | 'mtp' | 'coinHeight' | 'coinMtp', title: string, hint: string) {
    return <label>{title}<input aria-label={title} value={options[key]} inputMode="numeric" onChange={e => edit({ [key]: e.target.value })} /><small>{hint}</small></label>;
  }
  const requirementLabel = relative ? (options.unit === 'time' ? 'Delay · 512-second units' : 'Delay · blocks') : (options.unit === 'time' ? 'Absolute requirement · Unix seconds' : 'Absolute requirement · block height');
  return <div className="timelocks-lab">
    <section className="hero"><div className="hero-copy"><div className="hero-meta"><span className="chapter-tag">SCRIPTS / TIMELOCKS</span><span>FICTIONAL CONFIRMED UTXO</span></div><h1>The right key.<br /><span>The right time.</span></h1><p>A signature answers “who?” A timelock adds “when?” Build a signed spend and discover why a valid signature can still be too early.</p></div></section>
    <aside className="tl-intro"><Clock3 size={26} /><div><strong>Two checks. One spend.</strong><p>Script opcodes check the transaction’s lock fields. Chain rules check those fields against a candidate block’s height and median time past. Passing the first check does not make time advance.</p></div></aside>
    <section aria-label="Choose timelock kind" className="tl-kinds">{TIMELOCK_MODES.map(mode => <button key={mode.id} className={`panel tl-kind ${mode.id === options.mode ? 'selected' : ''}`} aria-pressed={mode.id === options.mode} onClick={() => preset(mode.id)}><span className="output-kicker">{mode.layer}</span><strong>{mode.title}</strong><p>{mode.description}</p></button>)}</section>
    <section className="panel tl-builder" aria-label="Timelock builder"><div className="tl-heading"><div><span className="output-kicker">01 / CREATE THE CONDITION</span><h2>{enforced ? 'The output sets the rule.' : 'The signer sets the delay.'}</h2></div><button className="text-button" onClick={() => preset(options.mode, options.unit)}><RotateCcw size={14} />Reset example</button></div>
      <div className="tl-unit-choice" role="group" aria-label="Lock units"><button className="secondary-button" aria-pressed={options.unit !== 'time'} onClick={() => preset(options.mode, relative ? 'blocks' : 'height')}>{relative ? 'Blocks since confirmation' : 'Block height'}</button><button className="secondary-button" aria-pressed={options.unit === 'time'} onClick={() => preset(options.mode, 'time')}>{relative ? 'Time since confirmation' : 'Unix timestamp'}</button></div>
      <div className="tl-controls">{field('value', requirementLabel, relative ? (options.unit === 'time' ? '169 units = 86,528 seconds (24h 2m 8s) in the preset. Valid range: 0–65,535 units.' : 'Valid range: 0–65,535 blocks. A block count is not a promised wall-clock duration.') : options.unit === 'time' ? date(options.value) : 'Below 500,000,000 means height; at or above it means a Unix timestamp.')}<label>Address network<select aria-label="Timelock address network" value={network} onChange={e => { pending.current = null; invalidate(); setNetwork(e.target.value as Network); setResult(null); }}><option value="mainnet">Mainnet</option><option value="testnet">Testnet</option></select><small>Changes address encoding, not the timing rules.</small></label></div>
      <p className="tl-note">{enforced ? <><LockKeyhole size={15} />The requirement lives in the previous output’s witness script. Changing it creates a different fictional output; it cannot edit an existing on-chain lock.</> : 'The requirement control configures the transaction fields through “Use matching lock fields”. The previous output only checks the key; its owner can sign a different spend with no delay.'}</p>
      <div className="tl-heading tl-field-heading"><h3>Set the spending transaction’s fields</h3><button className="secondary-button" onClick={matching}>Use matching lock fields</button></div>
      <div className="tl-controls three"><label>Transaction version<select aria-label="Timelock transaction version" value={options.version} onChange={e => edit({ version: e.target.value })}><option value="1">1 · BIP68 disabled</option><option value="2">2 · BIP68 available</option></select><small>CSV with these operands requires version 2.</small></label>{field('locktime', 'nLockTime · decimal', 'One absolute lock field for the entire transaction. Zero means no absolute limit.')}{field('sequence', 'nSequence · decimal', 'One field per input. This example has a single input. Bit 31 disables BIP68; all-final inputs disable nLockTime.')}</div>
      <div className="tl-quick-fields"><button className="text-button" onClick={() => edit({ sequence: '4294967295' })}>Set final · 0xffffffff</button><button className="text-button" onClick={() => edit({ sequence: '4294967294' })}>Set nonfinal · 0xfffffffe</button><span>0xfffffffe enables nLockTime while disabling BIP68. This lesson does not model replacement policy.</span></div>
    </section>
    <section className="panel tl-clock" aria-label="Modeled chain clock"><span className="output-kicker">02 / SET THE CHAIN CONTEXT</span><h2>Bitcoin’s clock is the chain.</h2><p>These values describe a hypothetical next block and an already confirmed ordinary UTXO. They are context for validation, not fields in the signed transaction.</p><div className="tl-controls">{field('height', 'Candidate block height', 'The height of the block that would include this spend, not the current tip height.')}{field('mtp', 'Previous-block median time past', date(options.mtp))}{field('coinHeight', 'UTXO confirmation height', 'The block containing the output being spent; it must precede the candidate.')}{field('coinMtp', 'MTP before UTXO confirmation', date(options.coinMtp))}</div><p className="tl-note">Median time past (MTP) is the median of the previous 11 block timestamps. Timestamp locks use this chain clock, not your computer’s clock or the candidate header timestamp. Relative time starts at the MTP of the block before the UTXO’s confirmation block.</p>
      <button className="primary-button" disabled={runtime.busy || runtime.status.state !== 'ready'} onClick={() => run()}>Build signed spend & check locks<Check size={16} /></button><p className="tl-note">Public learning key 1 spends a fictional 100,000-sat output to key 2’s native SegWit address. The output is 99,000 sats; the fixed fee is 1,000 sats. Each build signs the chosen fields, including deliberately incompatible examples.</p>
    </section>
    {runtime.error && <p className="input-error" role="alert">{runtime.error}</p>}
    {!result && !runtime.error && <p className="tl-pending" role="status">{runtime.busy ? 'Python is building and checking the signed example…' : 'Fields changed. Build the spend to see the new script and timing checks.'}</p>}
    {result && <>
      <section className="panel tl-verdict" aria-label="Timelock result" aria-live="polite"><div className="tl-heading"><div><span className="output-kicker">03 / CHECK BOTH GATES</span><h2 data-testid="timelock-verdict">{result.eligible ? 'The modeled timing checks pass.' : !result.scriptPass ? 'Fix the spending fields first.' : 'Valid script. Still too early.'}</h2></div><span className={`tl-status ${result.eligible ? 'pass' : 'wait'}`}>{result.eligible ? 'TIMING ELIGIBLE' : !result.scriptPass ? 'SCRIPT REJECTED' : 'WAIT FOR THE CHAIN'}</span></div><div className="tl-gates"><div><strong>Script + signature</strong><span>{result.scriptPass ? 'Pass' : 'Fail'}</span><small>Do these fields satisfy this spending condition?</small></div><div><strong>Chain timing</strong><span>{result.chainPass ? 'Pass' : 'Too early'}</span><small>Can these lock fields be included in this candidate?</small></div></div><div className="tl-check-list">{result.checks.map(check => <article key={check.label} className={check.passed ? 'pass' : 'wait'}><span>{check.passed ? 'PASS' : 'FAIL'}</span><div><strong>{check.label} <small>{check.layer}</small></strong><p>{check.explanation}</p></div></article>)}</div>
        <div className="tl-boundaries"><h3>Timing thresholds for the current fields</h3><p>First candidate height: <strong>{fmt(result.minimumHeight)}</strong> · earliest previous-block MTP: <strong>{fmt(result.minimumMtp)}</strong>. Both apply when both locks are active. The confirmed-UTXO assumption also applies.</p><div><button className="secondary-button" disabled={!result.absoluteActive && !result.relativeActive} onClick={() => clock('before')}>Try just before timing</button><button className="secondary-button" disabled={result.minimumHeight > 4294967295 || result.minimumMtp > 4294967295} onClick={() => clock('at')}>Meet timing thresholds</button></div><p className="tl-note">These buttons change chain context only. The signed bytes stay the same. A failing CLTV or CSV check still needs different transaction fields and a new signature.</p></div>
      </section>
      <section className="panel tl-bytes" aria-label="Timelock script and bytes"><span className="output-kicker">04 / FOLLOW THE CONDITION INTO BYTES</span><h2>{enforced ? 'A rule committed by the output.' : 'A key-only output. A delayed transaction.'}</h2><h3>Previous output’s witness script</h3><code className="tl-assembly">{result.assembly}</code><p className="tl-note">{enforced ? `The lock operand is pushed, ${options.mode === 'cltv' ? 'CLTV' : 'CSV'} checks it without removing it, OP_DROP removes it, then the public key verifies the signature with OP_CHECKSIG.` : 'The script contains only a public key and OP_CHECKSIG. The delay belongs to this signed transaction, not to the output’s spending rule.'}</p><code>{result.script}</code><details><summary>P2WSH address and previous locking script</summary><code>{result.address}</code><code>{result.previousScript}</code><p>The address commits to SHA-256 of the witness script. The spend’s witness supplies the signature and script; its scriptSig is empty.</p></details><div className="tl-wire-fields"><div><h3>nLockTime</h3><strong>{fmt(result.locktime)}</strong><code>{result.locktimeHex}</code><span>4 bytes · little-endian · {result.absoluteActive ? 'active' : 'inactive'}</span></div><div><h3>nSequence</h3><strong>{fmt(result.sequence)}</strong><code>{result.sequenceHex}</code><span>4 bytes · little-endian · BIP68 {result.relativeActive ? 'active' : 'inactive'}</span></div></div><dl className="tl-bit-fields"><div><dt>Bit 31 · disable</dt><dd>{result.disableBit ? '1 · BIP68 disabled' : '0 · BIP68 available with v2'}</dd></div><div><dt>Bit 22 · units</dt><dd>{result.timeBit ? '1 · 512 seconds' : '0 · blocks'}</dd></div><div><dt>Bits 0–15 · value</dt><dd>{fmt(result.masked)}</dd></div></dl><p className="tl-note">Other sequence bits are ignored by BIP68/CSV comparisons. {result.relativeActive ? `The effective relative delay is ${fmt(result.effectiveDelay)} ${result.timeBit ? 'seconds of chain MTP' : 'blocks'}.` : 'The unit and value bits have no relative-lock effect while BIP68 is inactive.'}</p>
        <details><summary>Signed transaction, digest, and witness</summary><div className="tl-heading"><h3>{result.vsize} vB · {fmt(result.fee)} sats fee · {(result.fee / result.vsize).toFixed(2)} sat/vB</h3><CopyCode label="Copy signed hex" value={result.hex} /></div><code>{result.hex}</code><h4>TXID</h4><code>{result.txid}</code><h4>WTXID</h4><code>{result.wtxid}</code><h4>BIP143 digest · SIGHASH_ALL</h4><code>{result.digest}</code><h4>Witness item 1 · signature with SIGHASH byte</h4><code>{result.signature}</code><h4>Witness item 2 · script</h4><code>{result.script}</code><p>The previous amount and script are supplied signing context. Candidate height and MTP are not signed fields.</p></details>
        <details><summary>Create this exact spend with Python</summary><div className="tl-heading"><h3>Build and sign with python-bitcoin-utils</h3><CopyCode label="Copy Python" value={result.python} /></div><pre>{result.python}</pre><p>This code produces the displayed signed bytes, including experiments that would fail script or timing checks. It does not broadcast or validate chain eligibility.</p></details>
      </section>
    </>}
    <details className="panel tl-scope"><summary>What to remember, and what this lab models</summary><ul><li><strong>nLockTime is absolute.</strong> It is one transaction field. Heights are below 500,000,000; timestamps are at or above it. Equality is still too early: the field must be strictly below candidate height or previous-block MTP. All-final input sequences bypass it.</li><li><strong>BIP68 is relative.</strong> Version ≥ 2 and a clear disable bit make each input’s sequence constrain UTXO age. Equality at confirmation height + delay (or prior-confirmation MTP + encoded seconds) is sufficient.</li><li><strong>CLTV and CSV enforce a requirement in Script.</strong> They compare an operand to the spending transaction’s fields; they do not read the current clock. CLTV also rejects a final spending input; CSV checks version, disable bit, unit, and masked minimum.</li><li><strong>Waiting does not fix a bad script argument.</strong> Time can satisfy chain timing, but insufficient or incompatible lock fields require changing and re-signing the transaction. When changing a script requirement here, you construct a different fictional locked output.</li><li><strong>These are native P2WSH examples.</strong> CLTV and CSV can also appear in legacy scripts or Taproot script paths. Transaction locks also apply without a script opcode.</li><li><strong>Scope:</strong> one confirmed ordinary UTXO, fixed key-and-lock templates, real library construction/signing and signature verification, and modeled consensus timing checks. This is not a general Script interpreter, full node-policy validation, chain lookup, mempool admission, coinbase maturity lesson, or broadcasting. Sequence locks across multiple inputs take the most restrictive height and time limits. This lab starts with CSV operands whose disable bit is clear; a CSV operand with bit 31 set acts as a NOP.</li></ul></details>
    <div className="lesson-sources">Read the specifications: {[65, 68, 112, 113].map(bip => <a key={bip} href={`https://github.com/bitcoin/bips/blob/master/bip-${String(bip).padStart(4, '0')}.mediawiki`} target="_blank" rel="noreferrer">BIP {bip}</a>)}</div>
  </div>;
}
