import { useEffect, useState } from 'react';
import { ArrowRight, Network, Pause, Play, Plus, RotateCcw } from 'lucide-react';
import { addCompetition, advanceSimulation, initialSimulation, LINKS, NODES } from './networkSimulation';
import type { NodeId, NodeStatus, SimulationOptions } from './networkSimulation';
import type { TransactionDraft } from './types';
import './journey.css';

const STATUS: Record<NodeStatus, string> = { unseen: 'Not seen', requested: 'Requesting bytes', checking: 'Modeling checks', accepted: 'In mempool', policy: 'Below local minimum', missing: 'Missing input', offline: 'Disconnected' };

export function TransactionJourney({ txid, hex, fee, vsize, inputs, scripts, enabled = true }: {
  enabled?: boolean;
  txid: string; hex: string; fee: number; vsize: number; inputs: TransactionDraft['inputs']; scripts: string[];
}) {
  const [options, setOptions] = useState<SimulationOptions>({ feeRate: fee / vsize, selectiveMinimum: 5, missingAtC: false, offlineE: false });
  const [state, setState] = useState(() => initialSimulation(options));
  const [playing, setPlaying] = useState(false);
  const [selected, setSelected] = useState<NodeId>('A');
  const [view, setView] = useState<'network' | 'mempool'>('network');
  const accepted = NODES.filter((node) => state.nodes[node.id] === 'accepted').length;
  const wave = state.wave ?? 0;
  const latestWave = state.logs.filter((log) => log.wave === wave);
  const status = state.nodes[selected];
  const entries = [...state.pools[selected], ...(status === 'accepted' ? [{ id: 'yours', label: 'Your signed transaction', vsize, feeRate: fee / vsize }] : [])].sort((a, b) => b.feeRate - a.feeRate || a.id.localeCompare(b.id));
  const maxSize = Math.max(...entries.map((entry) => entry.vsize), 1);
  useEffect(() => {
    if (!enabled || !playing || !state.queue.length) return;
    const timer = setTimeout(() => setState((previous) => advanceSimulation(previous, options)), 1050);
    return () => clearTimeout(timer);
  }, [playing, state.queue, options, enabled]);
  function restart(next = options) { setPlaying(false); setOptions(next); setState(initialSimulation(next)); }
  function selectNode(node: NodeId) { setSelected(node); }

  return <section id="transaction-journey" className="panel journey" aria-label="Transaction propagation and mempools">
    <div className="journey-heading"><div><span className="output-kicker">03 / THE TRANSACTION JOURNEY</span><h2>One transaction.<br /><span>Many independent nodes.</span></h2></div><span className="journey-badge"><Network size={14} />LOCAL SIMULATION</span></div>
    <p className="journey-intro">Follow your signed transaction through a small peer network. Connected peers act in parallel, while each new relay still travels one hop at a time.</p>
    <p className="journey-model-note">Fictional starting UTXOs · consensus checks assumed, not executed · no real broadcast</p>
    <div className="journey-identity"><span>YOUR SIGNED TXID</span><code>{txid}</code><div><span>{vsize.toLocaleString()} vB</span><span>{fee.toLocaleString()} sats fee</span><span>{(fee / vsize).toFixed(2)} sat/vB</span><strong>0 confirmations</strong></div></div>
    <ol className="journey-progress" aria-label="Journey progress"><li className="done">Signed</li><li className={state.logs.length ? 'done' : ''}>Propagating</li><li className={accepted ? 'done' : ''}>{accepted} / 5 mempools</li><li>Awaiting a block</li></ol>
    <details className="journey-assumptions"><summary>What is real, and what is simulated?</summary><p>The signed bytes, transaction ID, and size come from python-bitcoin-utils. Fees use your supplied previous amounts. Messages, timing, background entries, and node decisions are educational models; no transaction is sent to the Bitcoin network.</p><p>For this starting world, the inputs below are assumed to exist as unspent outputs. Signature and full consensus validation are assumed to pass, not executed here. Only C’s illustrated fee threshold and optional missing-input condition affect admission. These are not Bitcoin Core defaults or a complete policy implementation.</p><div className="journey-utxos">{inputs.map((input, i) => <div key={i}><strong>Assumed UTXO {i + 1}</strong><code>{input.txid.trim()}:{input.vout}</code><span>{input.amount} sats</span><code>{scripts[i]}</code></div>)}</div><p>Peers already have connections. The inv → getdata → tx exchange is simplified; scheduling and duplicate handling do not reproduce a particular node implementation. Background entries represent independent transactions with different inputs.</p><details><summary>Inspect the exact bytes being propagated</summary><code className="tx-selected-hex">{hex}</code></details></details>
    <div className="journey-scenarios"><label>C’s illustrative minimum<select aria-label="Node C minimum fee rate" value={options.selectiveMinimum} onChange={(event) => restart({ ...options, selectiveMinimum: Number(event.target.value) })}>{[0, 1, 5, 10, 20].map((rate) => <option key={rate} value={rate}>{rate} sat/vB</option>)}</select></label><label className="journey-check"><input type="checkbox" checked={options.missingAtC} onChange={(event) => restart({ ...options, missingAtC: event.target.checked })} />C lacks a referenced output</label><label className="journey-check"><input type="checkbox" checked={options.offlineE} onChange={(event) => restart({ ...options, offlineE: event.target.checked })} />Disconnect E</label><small>Changing a scenario restarts propagation.</small></div>
    <div className="journey-controls"><div><button type="button" className="primary-button" disabled={!state.queue.length} onClick={() => setPlaying(!playing)}>{playing && state.queue.length ? <Pause size={14} /> : <Play size={14} />}{playing && state.queue.length ? 'Pause propagation' : state.logs.length ? 'Play propagation' : 'Start propagation'}</button><button type="button" className="secondary-button" disabled={!state.queue.length} onClick={() => { setPlaying(false); setState((previous) => advanceSimulation(previous, options)); }}>Next wave<ArrowRight size={14} /></button><button type="button" className="icon-button" aria-label="Restart propagation" onClick={() => restart()}><RotateCcw size={16} /></button></div><span>{state.queue.length ? `${wave} parallel ${wave === 1 ? 'wave' : 'waves'} · ${state.logs.length} messages` : `Settled after ${wave} waves · still unconfirmed`}</span></div>
    <div className="journey-tabs segmented" role="group" aria-label="Journey view"><button type="button" aria-pressed={view === 'network'} className={view === 'network' ? 'selected' : ''} onClick={() => setView('network')}>Peer network</button><button type="button" aria-pressed={view === 'mempool'} className={view === 'mempool' ? 'selected' : ''} onClick={() => setView('mempool')}>Compare mempools</button></div>
    {view === 'network' ? <div className="journey-map" aria-label="Peer connections">
      <svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{LINKS.map(([a, b]) => { const start = NODES.find((node) => node.id === a)!; const end = NODES.find((node) => node.id === b)!; const active = latestWave.some(({ event }) => (event.from === a && event.to === b) || (event.from === b && event.to === a)); return <line key={a + b} x1={start.x} y1={start.y} x2={end.x} y2={end.y} className={active ? 'active' : ''} />; })}</svg>
      {NODES.map((node) => <button key={node.id} type="button" style={{ left: `${node.x}%`, top: `${node.y}%` }} className={`journey-node node-${state.nodes[node.id]} ${selected === node.id ? 'selected' : ''}`} aria-label={`Node ${node.id}: ${node.name}, ${STATUS[state.nodes[node.id]]}`} aria-pressed={selected === node.id} onClick={() => selectNode(node.id)}><span>{node.id}</span><strong>{node.name}</strong><small>{STATUS[state.nodes[node.id]]}</small></button>)}
      <span className="journey-map-caption">Connections are illustrative. Nodes do not share one global mempool.</span>
    </div> : <div className="journey-pool-comparison">{NODES.map((node) => <button type="button" key={node.id} aria-pressed={selected === node.id} onClick={() => selectNode(node.id)} className={selected === node.id ? 'selected' : ''}><strong>{node.id} · {node.name}</strong><span>{state.pools[node.id].length + (state.nodes[node.id] === 'accepted' ? 1 : 0)} entries</span><small>{STATUS[state.nodes[node.id]]}</small>{state.nodes[node.id] === 'accepted' && <span className="journey-your-chip">Your transaction</span>}</button>)}</div>}
    <div className="journey-event" role="status"><span>{wave ? `WAVE ${String(wave).padStart(2, '0')} · ${latestWave.length} ${latestWave.length === 1 ? 'MESSAGE' : 'MESSAGES'} IN PARALLEL` : 'READY TO RELAY'}</span>{latestWave.length ? <ul>{latestWave.map((log, index) => <li key={index}>{log.text}</li>)}</ul> : <p>Your wallet has signed the transaction. Start propagation to submit its bytes to node A.</p>}</div>
    <div className="journey-inspection"><section className="journey-decision" aria-label="Selected node decision"><span className="output-kicker">NODE {selected} / LOCAL DECISION</span><h3>{STATUS[status]}</h3><dl><div><dt>Referenced outputs</dt><dd>{selected === 'C' && options.missingAtC ? 'One missing in this scenario' : 'Assumed available and unspent'}</dd></div><div><dt>Signatures & consensus</dt><dd>Assumed valid · not executed</dd></div><div><dt>Illustrative fee threshold</dt><dd>{selected === 'C' ? options.selectiveMinimum : 0} sat/vB</dd></div><div><dt>Your fee rate</dt><dd>{(fee / vsize).toFixed(2)} sat/vB</dd></div></dl><p>{status === 'policy' ? 'A local policy decision does not establish consensus invalidity. Another node may accept the same transaction.' : status === 'missing' ? 'This node cannot assess the spend without its referenced output. A real node may obtain missing parents; this model stops here.' : status === 'accepted' ? 'Membership in this node’s mempool is not a confirmation or a promise of inclusion in the next block.' : status === 'offline' ? 'This node keeps its pre-existing illustrative mempool, but receives no new traffic while disconnected.' : 'Arrival, checking, and admission are separate events. This node has not admitted your transaction yet.'}</p></section>
    <section className="journey-mempool" aria-label={`Node ${selected} mempool`}><div className="journey-pool-heading"><div><span className="output-kicker">NODE {selected} / MEMPOOL</span><h3>{entries.length} unconfirmed entries</h3></div><button type="button" className="text-button" disabled={status === 'offline' || state.competitors >= 8} onClick={() => setState((previous) => addCompetition(previous, selected, selected === 'C' ? options.selectiveMinimum : 0))}><Plus size={14} />Add fee competition</button></div><p>Illustrative independent entries, sorted by fee rate. Bar length represents virtual size; this is not a FIFO queue or a complete mining selection algorithm.</p><div className="journey-entries">{entries.map((entry) => <div key={entry.id} className={`journey-entry ${entry.id === 'yours' ? 'yours' : ''}`}><div><strong>{entry.label}</strong><span>{entry.feeRate.toFixed(2)} sat/vB</span></div><div className="journey-size-track"><span style={{ width: `${entry.vsize / maxSize * 100}%` }} /></div><small>{entry.vsize.toLocaleString()} vB{entry.id === 'yours' ? ' · same signed transaction' : ' · fictional entry, no transaction bytes'}</small></div>)}</div><p>New competition appears only at the selected node in this snapshot experiment. It uses different inputs and does not replace your transaction. Parents, packages, eviction, and replacement are later topics.</p></section></div>
    <details className="journey-history"><summary>Replay the message log ({state.logs.length})</summary><ol>{state.logs.map((log, i) => <li key={i}><span>Wave {log.wave}</span>{log.text}</li>)}</ol></details>
    <div className="journey-next"><strong>Next: from a mempool to a candidate block.</strong><p>The pool node can choose transactions from its local view. Selection and proof of work are separate steps. This simulation ends before mining, so the transaction still has zero confirmations.</p></div>
    <div className="lesson-sources">Reference: <a href="https://developer.bitcoin.org/devguide/p2p_network.html#transaction-broadcasting" target="_blank" rel="noreferrer">Transaction relay</a></div>
  </section>;
}
